; FIFA 15 Local FUT v0.2.39 - localhost-only routing
[Hook]
InitDelay=3000

[Origin]
LaunchFailureCheckRva=0x0390AD3F

[ProtoSSL]
Connect=0x0000000143066524
Send=0
Recv=0

[Redirect]
Count=6

Redirect.0.Hostname=spring14.gosredirector.ea.com
Redirect.0.Address=127.0.0.1
Redirect.0.Port=42230
Redirect.0.Secure=0

Redirect.1.Hostname=127.0.0.1
Redirect.1.SourcePort=10051
Redirect.1.Address=127.0.0.1
Redirect.1.Port=10051
Redirect.1.Secure=0

Redirect.2.Hostname=127.0.0.1
Redirect.2.SourcePort=17502
Redirect.2.Address=127.0.0.1
Redirect.2.Port=17502
Redirect.2.Secure=0

Redirect.3.Hostname=127.0.0.1
Redirect.3.SourcePort=42232
Redirect.3.Address=127.0.0.1
Redirect.3.Port=42232
Redirect.3.Secure=0

Redirect.4.Hostname=127.0.0.1
Redirect.4.SourcePort=8199
Redirect.4.Address=127.0.0.1
Redirect.4.Port=8199
Redirect.4.Secure=0

Redirect.5.Hostname=127.0.0.1
Redirect.5.SourcePort=8099
Redirect.5.Address=127.0.0.1
Redirect.5.Port=8099
Redirect.5.Secure=0
